### ISSUE TITLE
Пагинация по дням во "Времени намаза"

### ISSUE THREAD

**Issue by blablatdinov** [blablatdinov/tg-quranbot#1206]
Добавить к клавиатуре кнопки для переключения на предыдущий и следующий день:

---

Время намаза для г. Казань (02.09.2024)

Иртәнге: 02:26
Восход: 04:50
Өйлә: 12:00
Икенде: 16:20
Ахшам: 18:35
Ястү: 20:27

<table>
    <tbody>
        <tr>
            <td>❌</td>
            <td>❌</td>
            <td>❌</td>
            <td>❌</td>
            <td>❌</td>
        </tr>
        <tr>
            <td colspan="2">01.09</td>
            <td colspan="3">03.09</td>
        </tr>
    </tbody>
</table>

**Comment by 0pdd** [comment]
@blablatdinov all 10 puzzles are solved here: [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown]().

**Comment by 0pdd** [comment]
@blablatdinov 10 puzzles [#1211](https://github.com/blablatdinov/tg-quranbot/issues/1211), [#1212](https://github.com/blablatdinov/tg-quranbot/issues/1212), [#1213](https://github.com/blablatdinov/tg-quranbot/issues/1213), [#1214](https://github.com/blablatdinov/tg-quranbot/issues/1214), [#1215](https://github.com/blablatdinov/tg-quranbot/issues/1215), [#1216](https://github.com/blablatdinov/tg-quranbot/issues/1216), [#1217](https://github.com/blablatdinov/tg-quranbot/issues/1217), [#1218](https://github.com/blablatdinov/tg-quranbot/issues/1218), [#1219](https://github.com/blablatdinov/tg-quranbot/issues/1219), [#1220](https://github.com/blablatdinov/tg-quranbot/issues/1220) are still not solved.

**Comment by 0pdd** [comment]
@blablatdinov 11 puzzles [#1211](https://github.com/blablatdinov/tg-quranbot/issues/1211), [#1212](https://github.com/blablatdinov/tg-quranbot/issues/1212), [#1213](https://github.com/blablatdinov/tg-quranbot/issues/1213), [#1215](https://github.com/blablatdinov/tg-quranbot/issues/1215), [#1217](https://github.com/blablatdinov/tg-quranbot/issues/1217), [#1218](https://github.com/blablatdinov/tg-quranbot/issues/1218), [#1219](https://github.com/blablatdinov/tg-quranbot/issues/1219), [#1220](https://github.com/blablatdinov/tg-quranbot/issues/1220), [#1223](https://github.com/blablatdinov/tg-quranbot/issues/1223), [#1224](https://github.com/blablatdinov/tg-quranbot/issues/1224), [#1225](https://github.com/blablatdinov/tg-quranbot/issues/1225) are still not solved; solved: [#1214](https://github.com/blablatdinov/tg-quranbot/issues/1214), [#1216](https://github.com/blablatdinov/tg-quranbot/issues/1216).

**Comment by 0pdd** [comment]
@blablatdinov 13 puzzles [#1211](https://github.com/blablatdinov/tg-quranbot/issues/1211), [#1212](https://github.com/blablatdinov/tg-quranbot/issues/1212), [#1213](https://github.com/blablatdinov/tg-quranbot/issues/1213), [#1217](https://github.com/blablatdinov/tg-quranbot/issues/1217), [#1218](https://github.com/blablatdinov/tg-quranbot/issues/1218), [#1219](https://github.com/blablatdinov/tg-quranbot/issues/1219), [#1220](https://github.com/blablatdinov/tg-quranbot/issues/1220), [#1223](https://github.com/blablatdinov/tg-quranbot/issues/1223), [#1224](https://github.com/blablatdinov/tg-quranbot/issues/1224), [#1225](https://github.com/blablatdinov/tg-quranbot/issues/1225), [#1227](https://github.com/blablatdinov/tg-quranbot/issues/1227), [#1228](https://github.com/blablatdinov/tg-quranbot/issues/1228), [#1229](https://github.com/blablatdinov/tg-quranbot/issues/1229) are still not solved; solved: [#1214](https://github.com/blablatdinov/tg-quranbot/issues/1214), [#1215](https://github.com/blablatdinov/tg-quranbot/issues/1215), [#1216](https://github.com/blablatdinov/tg-quranbot/issues/1216).

**Comment by 0pdd** [comment]
@blablatdinov 12 puzzles [#1211](https://github.com/blablatdinov/tg-quranbot/issues/1211), [#1212](https://github.com/blablatdinov/tg-quranbot/issues/1212), [#1213](https://github.com/blablatdinov/tg-quranbot/issues/1213), [#1217](https://github.com/blablatdinov/tg-quranbot/issues/1217), [#1218](https://github.com/blablatdinov/tg-quranbot/issues/1218), [#1219](https://github.com/blablatdinov/tg-quranbot/issues/1219), [#1220](https://github.com/blablatdinov/tg-quranbot/issues/1220), [#1223](https://github.com/blablatdinov/tg-quranbot/issues/1223), [#1224](https://github.com/blablatdinov/tg-quranbot/issues/1224), [#1225](https://github.com/blablatdinov/tg-quranbot/issues/1225), [#1227](https://github.com/blablatdinov/tg-quranbot/issues/1227), [#1229](https://github.com/blablatdinov/tg-quranbot/issues/1229) are still not solved; solved: [#1214](https://github.com/blablatdinov/tg-quranbot/issues/1214), [#1215](https://github.com/blablatdinov/tg-quranbot/issues/1215), [#1216](https://github.com/blablatdinov/tg-quranbot/issues/1216), [#1228](https://github.com/blablatdinov/tg-quranbot/issues/1228).

**Comment by 0pdd** [comment]
@blablatdinov 12 puzzles [#1211](https://github.com/blablatdinov/tg-quranbot/issues/1211), [#1212](https://github.com/blablatdinov/tg-quranbot/issues/1212), [#1213](https://github.com/blablatdinov/tg-quranbot/issues/1213), [#1217](https://github.com/blablatdinov/tg-quranbot/issues/1217), [#1218](https://github.com/blablatdinov/tg-quranbot/issues/1218), [#1219](https://github.com/blablatdinov/tg-quranbot/issues/1219), [#1220](https://github.com/blablatdinov/tg-quranbot/issues/1220), [#1223](https://github.com/blablatdinov/tg-quranbot/issues/1223), [#1224](https://github.com/blablatdinov/tg-quranbot/issues/1224), [#1225](https://github.com/blablatdinov/tg-quranbot/issues/1225), [#1229](https://github.com/blablatdinov/tg-quranbot/issues/1229), [#1232](https://github.com/blablatdinov/tg-quranbot/issues/1232) are still not solved; solved: [#1214](https://github.com/blablatdinov/tg-quranbot/issues/1214), [#1215](https://github.com/blablatdinov/tg-quranbot/issues/1215), [#1216](https://github.com/blablatdinov/tg-quranbot/issues/1216), [#1227](https://github.com/blablatdinov/tg-quranbot/issues/1227), [#1228](https://github.com/blablatdinov/tg-quranbot/issues/1228).

**Comment by 0pdd** [comment]
@blablatdinov 10 puzzles [#1211](https://github.com/blablatdinov/tg-quranbot/issues/1211), [#1212](https://github.com/blablatdinov/tg-quranbot/issues/1212), [#1217](https://github.com/blablatdinov/tg-quranbot/issues/1217), [#1218](https://github.com/blablatdinov/tg-quranbot/issues/1218), [#1219](https://github.com/blablatdinov/tg-quranbot/issues/1219), [#1220](https://github.com/blablatdinov/tg-quranbot/issues/1220), [#1223](https://github.com/blablatdinov/tg-quranbot/issues/1223), [#1224](https://github.com/blablatdinov/tg-quranbot/issues/1224), [#1225](https://github.com/blablatdinov/tg-quranbot/issues/1225), [#1232](https://github.com/blablatdinov/tg-quranbot/issues/1232) are still not solved; solved: [#1213](https://github.com/blablatdinov/tg-quranbot/issues/1213), [#1214](https://github.com/blablatdinov/tg-quranbot/issues/1214), [#1215](https://github.com/blablatdinov/tg-quranbot/issues/1215), [#1216](https://github.com/blablatdinov/tg-quranbot/issues/1216), [#1227](https://github.com/blablatdinov/tg-quranbot/issues/1227), [#1228](https://github.com/blablatdinov/tg-quranbot/issues/1228), [#1229](https://github.com/blablatdinov/tg-quranbot/issues/1229).

**Comment by 0pdd** [comment]
@blablatdinov 9 puzzles [#1211](https://github.com/blablatdinov/tg-quranbot/issues/1211), [#1212](https://github.com/blablatdinov/tg-quranbot/issues/1212), [#1217](https://github.com/blablatdinov/tg-quranbot/issues/1217), [#1218](https://github.com/blablatdinov/tg-quranbot/issues/1218), [#1219](https://github.com/blablatdinov/tg-quranbot/issues/1219), [#1220](https://github.com/blablatdinov/tg-quranbot/issues/1220), [#1223](https://github.com/blablatdinov/tg-quranbot/issues/1223), [#1224](https://github.com/blablatdinov/tg-quranbot/issues/1224), [#1225](https://github.com/blablatdinov/tg-quranbot/issues/1225) are still not solved; solved: [#1213](https://github.com/blablatdinov/tg-quranbot/issues/1213), [#1214](https://github.com/blablatdinov/tg-quranbot/issues/1214), [#1215](https://github.com/blablatdinov/tg-quranbot/issues/1215), [#1216](https://github.com/blablatdinov/tg-quranbot/issues/1216), [#1227](https://github.com/blablatdinov/tg-quranbot/issues/1227), [#1228](https://github.com/blablatdinov/tg-quranbot/issues/1228), [#1229](https://github.com/blablatdinov/tg-quranbot/issues/1229), [#1232](https://github.com/blablatdinov/tg-quranbot/issues/1232).

**Comment by 0pdd** [comment]
@blablatdinov 8 puzzles [#1211](https://github.com/blablatdinov/tg-quranbot/issues/1211), [#1212](https://github.com/blablatdinov/tg-quranbot/issues/1212), [#1217](https://github.com/blablatdinov/tg-quranbot/issues/1217), [#1218](https://github.com/blablatdinov/tg-quranbot/issues/1218), [#1219](https://github.com/blablatdinov/tg-quranbot/issues/1219), [#1220](https://github.com/blablatdinov/tg-quranbot/issues/1220), [#1223](https://github.com/blablatdinov/tg-quranbot/issues/1223), [#1224](https://github.com/blablatdinov/tg-quranbot/issues/1224) are still not solved; solved: [#1213](https://github.com/blablatdinov/tg-quranbot/issues/1213), [#1214](https://github.com/blablatdinov/tg-quranbot/issues/1214), [#1215](https://github.com/blablatdinov/tg-quranbot/issues/1215), [#1216](https://github.com/blablatdinov/tg-quranbot/issues/1216), [#1225](https://github.com/blablatdinov/tg-quranbot/issues/1225), [#1227](https://github.com/blablatdinov/tg-quranbot/issues/1227), [#1228](https://github.com/blablatdinov/tg-quranbot/issues/1228), [#1229](https://github.com/blablatdinov/tg-quranbot/issues/1229), [#1232](https://github.com/blablatdinov/tg-quranbot/issues/1232).

**Comment by 0pdd** [comment]
@blablatdinov 6 puzzles [#1211](https://github.com/blablatdinov/tg-quranbot/issues/1211), [#1212](https://github.com/blablatdinov/tg-quranbot/issues/1212), [#1219](https://github.com/blablatdinov/tg-quranbot/issues/1219), [#1220](https://github.com/blablatdinov/tg-quranbot/issues/1220), [#1223](https://github.com/blablatdinov/tg-quranbot/issues/1223), [#1224](https://github.com/blablatdinov/tg-quranbot/issues/1224) are still not solved; solved: [#1213](https://github.com/blablatdinov/tg-quranbot/issues/1213), [#1214](https://github.com/blablatdinov/tg-quranbot/issues/1214), [#1215](https://github.com/blablatdinov/tg-quranbot/issues/1215), [#1216](https://github.com/blablatdinov/tg-quranbot/issues/1216), [#1217](https://github.com/blablatdinov/tg-quranbot/issues/1217), [#1218](https://github.com/blablatdinov/tg-quranbot/issues/1218), [#1225](https://github.com/blablatdinov/tg-quranbot/issues/1225), [#1227](https://github.com/blablatdinov/tg-quranbot/issues/1227), [#1228](https://github.com/blablatdinov/tg-quranbot/issues/1228), [#1229](https://github.com/blablatdinov/tg-quranbot/issues/1229), [#1232](https://github.com/blablatdinov/tg-quranbot/issues/1232).

**Comment by 0pdd** [comment]
@blablatdinov 4 puzzles [#1211](https://github.com/blablatdinov/tg-quranbot/issues/1211), [#1212](https://github.com/blablatdinov/tg-quranbot/issues/1212), [#1223](https://github.com/blablatdinov/tg-quranbot/issues/1223), [#1224](https://github.com/blablatdinov/tg-quranbot/issues/1224) are still not solved; solved: [#1213](https://github.com/blablatdinov/tg-quranbot/issues/1213), [#1214](https://github.com/blablatdinov/tg-quranbot/issues/1214), [#1215](https://github.com/blablatdinov/tg-quranbot/issues/1215), [#1216](https://github.com/blablatdinov/tg-quranbot/issues/1216), [#1217](https://github.com/blablatdinov/tg-quranbot/issues/1217), [#1218](https://github.com/blablatdinov/tg-quranbot/issues/1218), [#1219](https://github.com/blablatdinov/tg-quranbot/issues/1219), [#1220](https://github.com/blablatdinov/tg-quranbot/issues/1220), [#1225](https://github.com/blablatdinov/tg-quranbot/issues/1225), [#1227](https://github.com/blablatdinov/tg-quranbot/issues/1227), [#1228](https://github.com/blablatdinov/tg-quranbot/issues/1228), [#1229](https://github.com/blablatdinov/tg-quranbot/issues/1229), [#1232](https://github.com/blablatdinov/tg-quranbot/issues/1232).

**Comment by 0pdd** [comment]
@blablatdinov 3 puzzles [#1211](https://github.com/blablatdinov/tg-quranbot/issues/1211), [#1223](https://github.com/blablatdinov/tg-quranbot/issues/1223), [#1224](https://github.com/blablatdinov/tg-quranbot/issues/1224) are still not solved; solved: [#1212](https://github.com/blablatdinov/tg-quranbot/issues/1212), [#1213](https://github.com/blablatdinov/tg-quranbot/issues/1213), [#1214](https://github.com/blablatdinov/tg-quranbot/issues/1214), [#1215](https://github.com/blablatdinov/tg-quranbot/issues/1215), [#1216](https://github.com/blablatdinov/tg-quranbot/issues/1216), [#1217](https://github.com/blablatdinov/tg-quranbot/issues/1217), [#1218](https://github.com/blablatdinov/tg-quranbot/issues/1218), [#1219](https://github.com/blablatdinov/tg-quranbot/issues/1219), [#1220](https://github.com/blablatdinov/tg-quranbot/issues/1220), [#1225](https://github.com/blablatdinov/tg-quranbot/issues/1225), [#1227](https://github.com/blablatdinov/tg-quranbot/issues/1227), [#1228](https://github.com/blablatdinov/tg-quranbot/issues/1228), [#1229](https://github.com/blablatdinov/tg-quranbot/issues/1229), [#1232](https://github.com/blablatdinov/tg-quranbot/issues/1232).

**Comment by 0pdd** [comment]
@blablatdinov 2 puzzles [#1223](https://github.com/blablatdinov/tg-quranbot/issues/1223), [#1224](https://github.com/blablatdinov/tg-quranbot/issues/1224) are still not solved; solved: [#1211](https://github.com/blablatdinov/tg-quranbot/issues/1211), [#1212](https://github.com/blablatdinov/tg-quranbot/issues/1212), [#1213](https://github.com/blablatdinov/tg-quranbot/issues/1213), [#1214](https://github.com/blablatdinov/tg-quranbot/issues/1214), [#1215](https://github.com/blablatdinov/tg-quranbot/issues/1215), [#1216](https://github.com/blablatdinov/tg-quranbot/issues/1216), [#1217](https://github.com/blablatdinov/tg-quranbot/issues/1217), [#1218](https://github.com/blablatdinov/tg-quranbot/issues/1218), [#1219](https://github.com/blablatdinov/tg-quranbot/issues/1219), [#1220](https://github.com/blablatdinov/tg-quranbot/issues/1220), [#1225](https://github.com/blablatdinov/tg-quranbot/issues/1225), [#1227](https://github.com/blablatdinov/tg-quranbot/issues/1227), [#1228](https://github.com/blablatdinov/tg-quranbot/issues/1228), [#1229](https://github.com/blablatdinov/tg-quranbot/issues/1229), [#1232](https://github.com/blablatdinov/tg-quranbot/issues/1232).

**Comment by 0pdd** [comment]
@blablatdinov the puzzle [#1223](https://github.com/blablatdinov/tg-quranbot/issues/1223) is still not solved; solved: [#1211](https://github.com/blablatdinov/tg-quranbot/issues/1211), [#1212](https://github.com/blablatdinov/tg-quranbot/issues/1212), [#1213](https://github.com/blablatdinov/tg-quranbot/issues/1213), [#1214](https://github.com/blablatdinov/tg-quranbot/issues/1214), [#1215](https://github.com/blablatdinov/tg-quranbot/issues/1215), [#1216](https://github.com/blablatdinov/tg-quranbot/issues/1216), [#1217](https://github.com/blablatdinov/tg-quranbot/issues/1217), [#1218](https://github.com/blablatdinov/tg-quranbot/issues/1218), [#1219](https://github.com/blablatdinov/tg-quranbot/issues/1219), [#1220](https://github.com/blablatdinov/tg-quranbot/issues/1220), [#1224](https://github.com/blablatdinov/tg-quranbot/issues/1224), [#1225](https://github.com/blablatdinov/tg-quranbot/issues/1225), [#1227](https://github.com/blablatdinov/tg-quranbot/issues/1227), [#1228](https://github.com/blablatdinov/tg-quranbot/issues/1228), [#1229](https://github.com/blablatdinov/tg-quranbot/issues/1229), [#1232](https://github.com/blablatdinov/tg-quranbot/issues/1232).

**Comment by 0pdd** [comment]
@blablatdinov all 17 puzzles are solved here: [#1211](https://github.com/blablatdinov/tg-quranbot/issues/1211), [#1212](https://github.com/blablatdinov/tg-quranbot/issues/1212), [#1213](https://github.com/blablatdinov/tg-quranbot/issues/1213), [#1214](https://github.com/blablatdinov/tg-quranbot/issues/1214), [#1215](https://github.com/blablatdinov/tg-quranbot/issues/1215), [#1216](https://github.com/blablatdinov/tg-quranbot/issues/1216), [#1217](https://github.com/blablatdinov/tg-quranbot/issues/1217), [#1218](https://github.com/blablatdinov/tg-quranbot/issues/1218), [#1219](https://github.com/blablatdinov/tg-quranbot/issues/1219), [#1220](https://github.com/blablatdinov/tg-quranbot/issues/1220), [#1223](https://github.com/blablatdinov/tg-quranbot/issues/1223), [#1224](https://github.com/blablatdinov/tg-quranbot/issues/1224), [#1225](https://github.com/blablatdinov/tg-quranbot/issues/1225), [#1227](https://github.com/blablatdinov/tg-quranbot/issues/1227), [#1228](https://github.com/blablatdinov/tg-quranbot/issues/1228), [#1229](https://github.com/blablatdinov/tg-quranbot/issues/1229), [#1232](https://github.com/blablatdinov/tg-quranbot/issues/1232).
