### ISSUE TITLE
pyproject.toml:118: Поднять python target-version до "py312"

### ISSUE THREAD

**Issue by 0pdd** [blablatdinov/tg-quranbot#982]
The puzzle `360-bee10384` from #360 has to be resolved: 

https://github.com/blablatdinov/tg-quranbot/blob/3c83a562066717543817037d6f58540869e1060f/pyproject.toml#L118-L118

The puzzle was created by @blablatdinov on 20-Jun-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by blablatdinov** [comment]
Double of #753
